### ISSUE TITLE
It is possible to check only modified files?

### ISSUE THREAD

**Issue by joicecg** [abaplint/abaplint#2678]
I'm using the abaplint triggered by Jenkins in an ABAP Repository. But the rules always run for **all files** in the repository.
I would like to know if there is a way to configure the abaplint to run only for the modified files in a given pull request.

This is because I have many files, and the checks take a long time.

**Comment by larshp** [comment]
Hi,
I recommend not using Jenkins for anything, instead use the built-in pipelines like GitHub Actions, Gitlab Pipelines, Azure Pipelines, Bitbucket pipelines etc. But that's a different story 😄 

Typically I think its a bad idea to check only modified files,
A: "Everything is checked always for each commit" is very easy to understand and communicate, what qualifies for a modified file in git is difficult
B: Bugs in abaplint is continuously fixed, so a finding might occur outside the set of modified files
C: Only checking modified files makes it difficult to reproduce the exact behavior on local PC

For abapGit, https://github.com/abapGit/abapGit/runs/8259515028, it checks ~150k lines and 400+ objects in ~40 seconds

What is the size of your repository and how long time does it take? Also try running `abaplint -p` to check where the time is spent, example output when running for abapGit,

![image](https://user-images.githubusercontent.com/5888506/189578810-a46834d6-b97f-4e83-9dea-5cbf5630cb2a.png)

**Comment by OberstVonGatow** [comment]
@joicecg we got the same requirement. @larshp is right it's probable the best if you could just check all but we decided to push all our 20 Years old Custom Code to a Git Repository and only check rules for new changes. (Refactor everything would be nice but would take forever).

In Gitlab i fingered out two possible Pipeline Solutions  (for Gitlab only you would need to check Jenkins parameters on your own).

If you only want to check Files in the current commit:

```
run_abaplint:
    image: abaplint/abaplint
    only:
         - merge_request
    script:
        - git show --pretty="" --name-only $CI_COMMIT_SHA
        - mkdir scan
        - git show --pretty="" --name-only $CI_COMMIT_SHA | xargs -I {} cp '{}' scan
        - abaplint --outformat junit --outfile report.xml
    artifacts:
        reports:
            junit: report.xml
        expire_in: 1 yr
    tags:
        - sap
```

(Better for MergeRequest) If you want to check all files changed in this MergeRequest:
```
run_abaplint:
    image: abaplint/abaplint
    only:
         - merge_request
    script:
        - git diff-tree --name-only -r $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA
        - mkdir scan
        - git diff-tree --name-only -r $CI_MERGE_REQUEST_DIFF_BASE_SHA $CI_COMMIT_SHA | xargs -I {} cp '{}' scan
        - abaplint --outformat junit --outfile report.xml
    artifacts:
        reports:
            junit: report.xml
        expire_in: 1 yr
    tags:
        - sap
```
